version: '3.8'

services:
  redis:
    image: redis:alpine
    command: redis-server --port 16379 --requirepass develop
    container_name: redis_16379
    hostname: redis_16379
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 16379:16379
    volumes:
      - ./redis/data:/data
#    networks:
#      - spring-net
  mysql:
    hostname: rsupport-mysql
    image: library/mysql:5.7
    container_name: rsupport-mysql
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
      MYSQL_OPTS: "--allow-keywords --allow-public-key-retrieval"
    volumes:
      - ./mysql/data:/var/lib/mysql --user 1000
      - ./mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
#    networks:
#      - spring-net
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-rsupport-project
    volumes:
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rsupportdb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 8180:8180
#    networks:
#      - spring-net
#networks:
#  spring-net:
#    driver: bridge